- hosts: pvenodes
  become: yes
  tasks:

  - name: install sudo package
    apt:
      name: sudo
      update_cache: yes
      cache_valid_time: 3600
      state: latest

  - name: create Ansibleusr user
    user:
      name: ansibleusr
      shell: /bin/bash

  - name: add Ansibleusr ssh key
    authorized_key:
      user: ansibleusr
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMJ/0TAXIIpd7v97lbU7+AS+XL2dy1N3F/9XIhttH6mG ansible@homelab.lan"
      path: /root/.ssh/authorized_keys

  - name: add ansibleusr to sudoers
    copy:
      src: sudoer_ansibleusr
      dest: /etc/sudoers.d/ansibleusr
      owner: root
      group: root
      mode: 0440
